server:
  port: 8090

spring:
  application:
    name: customer
  Datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'

  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          formal_sql: 'true'

      hibernate:
          ddl-auto: update
          show-sql: 'true'

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

